GET http://localhost:8080/users
Accept: application/json

###

GET http://localhost:8080/users
Accept: application/xml

###

GET http://localhost:8080/users/1
Accept: application/json

###

GET http://localhost:8080/users-post/1
Accept: application/json

###

POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
  "name": "Vinnie",
  "birthDate": "2000-10-11T17:54:11.558+00:00"
}

###

POST http://localhost:8080/users
Accept: application/json
Content-Type: application/json

{
    "name": "b",
    "birthDate": "2000-10-11T17:54:11.558+00:00"
}

###

DELETE http://localhost:8080/users/4
Accept: application/json

###

POST http://localhost:8080/users
Accept: application/xml
Content-Type: application/xml

<item>
    <name>Bilu XML</name>
    <birthDate>2000-10-14T19:12:10.653+00:00</birthDate>
</item>

###